FROM python:3.7.9-slim
RUN apt-get update && apt-get install -y gcc && apt-get install -y default-libmysqlclient-dev

COPY blog /app/blog
COPY requirements.txt /app/blog
COPY common /app/common
COPY instance /app/instance
#COPY .env /app/blog
WORKDIR /app/blog

RUN pip install --upgrade pip

RUN pip install -r requirements.txt

CMD flask run --host ${FLASK_HOST} --port ${FLASK_BLOG_PORT}

#CMD ["flask", "run", "--port ${FLASK_BLOG_PORT}"]
